In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
sns.reset_defaults
sns.set_style(style='darkgrid')
sns.set_context(context='notebook')
import matplotlib.pyplot as plt
#plt.style.use('ggplot')
plt.rcParams["patch.force_edgecolor"] = True
plt.rcParams['figure.figsize'] = (20.0, 10.0)
font = {'size'   : 20}
plt.rc('font', **font)
plt.ion()
%matplotlib inline

In [5]:
st_vle_df = pd.read_csv('../data/raw/studentVle.csv')

In [6]:
vle_df = pd.read_csv('../data/raw/vle.csv')

In [7]:
df = pd.merge(st_vle_df, vle_df, how='outer', on = ['code_module', 'code_presentation', 'id_site'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10655376 entries, 0 to 10655375
Data columns (total 9 columns):
code_module          object
code_presentation    object
id_student           float64
id_site              int64
date                 float64
sum_click            float64
activity_type        object
week_from            float64
week_to              float64
dtypes: float64(5), int64(1), object(3)
memory usage: 812.9+ MB

In [5]:
st_vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
code_module          object
code_presentation    object
id_student           int64
id_site              int64
date                 int64
sum_click            int64
dtypes: int64(4), object(2)
memory usage: 487.8+ MB

In [20]:
st_vle.sample(10)

        code_module code_presentation  id_student  id_site  date  sum_click
7684881         FFF             2013J      605954   716322    55         13
2530950         CCC             2014J      682961   909338    15          1
7307304         FFF             2013J      498031   716440     3          1
3486688         DDD             2013B      539622   547303   116          7
297547          AAA             2014J      263543   877399   150          3
6964886         FFF             2013B      532968   527116   150         15
277449          AAA             2014J      518808   877066   114          2
7105875         FFF             2013B     2327494   526721   201          3
1605347         BBB             2014J      679716   913466    33          8
4790124         DDD             2014J      653768   813710     3          1

In [7]:
# st_vle.groupby(by='id_student').sum()[['sum_click']].sort_values('sum_click', ascending=False)

In [13]:
st_vle['id_student'].value_counts().head()

537811     6389
2088765    5240
298040     4978
630905     4916
2063578    4518
Name: id_student, dtype: int64

In [21]:
st_vle[st_vle['id_student'] == 682961]

        code_module code_presentation  id_student  id_site  date  sum_click
2414956         CCC             2014J      682961   909303   -18          1
2414957         CCC             2014J      682961   909304   -18          1
2414958         CCC             2014J      682961   909305   -18          1
2414959         CCC             2014J      682961   909306   -18          1
2414960         CCC             2014J      682961   909307   -18          1
2414961         CCC             2014J      682961   909308   -18          1
2414962         CCC             2014J      682961   909309   -18          1
2414963         CCC             2014J      682961   909310   -18          1
2414964         CCC             2014J      682961   909311   -18          1
2414965         CCC             2014J      682961   909312   -18          1
2414966         CCC             2014J      682961   909313   -18          1
2414967         CCC             2014J      682961   909314   -18          1
2414968         CCC             2014J      682961   909013   -18         16
2414969         CCC             2014J      682961   909315   -18          1
2414970         CCC             2014J      682961   909297   -18          1
2414971         CCC             2014J      682961   909298   -18          1
2414972         CCC             2014J      682961   909299   -18          1
2414973         CCC             2014J      682961   909302   -18          1
2414974         CCC             2014J      682961   909301   -18          1
2414975         CCC             2014J      682961   909300   -18          1
2414976         CCC             2014J      682961   909268   -18          1
2414977         CCC             2014J      682961   909269   -18          1
2414978         CCC             2014J      682961   909270   -18          1
2414979         CCC             2014J      682961   909271   -18          1
2414980         CCC             2014J      682961   909281   -18          2
2414981         CCC             2014J      682961   909284   -18          1
2414982         CCC             2014J      682961   909285   -18          1
2414983         CCC             2014J      682961   909286   -18          1
2414984         CCC             2014J      682961   909287   -18          1
2414985         CCC             2014J      682961   909288   -18          1
...             ...               ...         ...      ...   ...        ...
3091780         CCC             2014J      682961   909229   239          6
3091781         CCC             2014J      682961   909013   239          1
3091782         CCC             2014J      682961   909085   239          3
3091783         CCC             2014J      682961   909085   239          1
3091784         CCC             2014J      682961   909085   239         33
3106752         CCC             2014J      682961  1011837   241          1
3106753         CCC             2014J      682961   909015   241          4
3106754         CCC             2014J      682961   909018   241          3
3106755         CCC             2014J      682961   909062   241          1
3106756         CCC             2014J      682961   909013   241          3
3106757         CCC             2014J      682961  1016724   241          1
3106758         CCC             2014J      682961  1011838   241          1
3106759         CCC             2014J      682961  1011841   241          1
3111787         CCC             2014J      682961  1011840   242          1
3111788         CCC             2014J      682961  1011841   242          1
3111789         CCC             2014J      682961  1011842   242          1
3111790         CCC             2014J      682961   909231   242          1
3111791         CCC             2014J      682961  1016724   242          1
3111792         CCC             2014J      682961   909013   242          1
3111793         CCC             2014J      682961  1011839   242          1
3111794         CCC             2014J      682961  1011838   242          3
3111795         CCC             2014J      682961  1011837   242          4
3116469         CCC             2014J      682961   909015   246          1
3116470         CCC             2014J      682961   909013   246          2
3121193         CCC             2014J      682961   909233   255          1
3121194         CCC             2014J      682961   909232   255          1
3121195         CCC             2014J      682961   909013   255          2
3122377         CCC             2014J      682961   909013   258          1
3124800         CCC             2014J      682961   909013   267          1
3124801         CCC             2014J      682961   909016   267          1

[914 rows x 6 columns]